package programmer.ie.dictator.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table EXCEPTION_DATA.
 */
public class ExceptionData {

    private Long id;
    /**
     * Not-null value.
     */
    private String packageName;
    private Long exceptionTime;
    private Long exceptionType;
    private String exceptionClassName;
    private String exceptionMessage;
    private String stackTrace;
    private String throwClassName;
    private String throwFileName;
    private String throwLineNumber;
    private String throwMethodName;

    public ExceptionData() {
    }

    public ExceptionData(Long id) {
        this.id = id;
    }

    public ExceptionData(Long id, String packageName, Long exceptionTime, Long exceptionType, String exceptionClassName, String exceptionMessage, String stackTrace, String throwClassName, String throwFileName, String throwLineNumber, String throwMethodName) {
        this.id = id;
        this.packageName = packageName;
        this.exceptionTime = exceptionTime;
        this.exceptionType = exceptionType;
        this.exceptionClassName = exceptionClassName;
        this.exceptionMessage = exceptionMessage;
        this.stackTrace = stackTrace;
        this.throwClassName = throwClassName;
        this.throwFileName = throwFileName;
        this.throwLineNumber = throwLineNumber;
        this.throwMethodName = throwMethodName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public Long getExceptionTime() {
        return exceptionTime;
    }

    public void setExceptionTime(Long exceptionTime) {
        this.exceptionTime = exceptionTime;
    }

    public Long getExceptionType() {
        return exceptionType;
    }

    public void setExceptionType(Long exceptionType) {
        this.exceptionType = exceptionType;
    }

    public String getExceptionClassName() {
        return exceptionClassName;
    }

    public void setExceptionClassName(String exceptionClassName) {
        this.exceptionClassName = exceptionClassName;
    }

    public String getExceptionMessage() {
        return exceptionMessage;
    }

    public void setExceptionMessage(String exceptionMessage) {
        this.exceptionMessage = exceptionMessage;
    }

    public String getStackTrace() {
        return stackTrace;
    }

    public void setStackTrace(String stackTrace) {
        this.stackTrace = stackTrace;
    }

    public String getThrowClassName() {
        return throwClassName;
    }

    public void setThrowClassName(String throwClassName) {
        this.throwClassName = throwClassName;
    }

    public String getThrowFileName() {
        return throwFileName;
    }

    public void setThrowFileName(String throwFileName) {
        this.throwFileName = throwFileName;
    }

    public String getThrowLineNumber() {
        return throwLineNumber;
    }

    public void setThrowLineNumber(String throwLineNumber) {
        this.throwLineNumber = throwLineNumber;
    }

    public String getThrowMethodName() {
        return throwMethodName;
    }

    public void setThrowMethodName(String throwMethodName) {
        this.throwMethodName = throwMethodName;
    }

}
