package com.banba.dictator.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordingDaoConfig;
    private final DaoConfig recordingTextDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig exceptionDataDaoConfig;

    private final RecordingDao recordingDao;
    private final RecordingTextDao recordingTextDao;
    private final NoteDao noteDao;
    private final ExceptionDataDao exceptionDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordingDaoConfig = daoConfigMap.get(RecordingDao.class).clone();
        recordingDaoConfig.initIdentityScope(type);

        recordingTextDaoConfig = daoConfigMap.get(RecordingTextDao.class).clone();
        recordingTextDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        exceptionDataDaoConfig = daoConfigMap.get(ExceptionDataDao.class).clone();
        exceptionDataDaoConfig.initIdentityScope(type);

        recordingDao = new RecordingDao(recordingDaoConfig, this);
        recordingTextDao = new RecordingTextDao(recordingTextDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        exceptionDataDao = new ExceptionDataDao(exceptionDataDaoConfig, this);

        registerDao(Recording.class, recordingDao);
        registerDao(RecordingText.class, recordingTextDao);
        registerDao(Note.class, noteDao);
        registerDao(ExceptionData.class, exceptionDataDao);
    }

    public void clear() {
        recordingDaoConfig.getIdentityScope().clear();
        recordingTextDaoConfig.getIdentityScope().clear();
        noteDaoConfig.getIdentityScope().clear();
        exceptionDataDaoConfig.getIdentityScope().clear();
    }

    public RecordingDao getRecordingDao() {
        return recordingDao;
    }

    public RecordingTextDao getRecordingTextDao() {
        return recordingTextDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public ExceptionDataDao getExceptionDataDao() {
        return exceptionDataDao;
    }

}
