package com.banba.dictator.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECORDING.
 */
public class Recording {

    private Long id;
    /** Not-null value. */
    private String name;
    private java.util.Date starttime;

    public Recording() {
    }

    public Recording(Long id) {
        this.id = id;
    }

    public Recording(Long id, String name, java.util.Date starttime) {
        this.id = id;
        this.name = name;
        this.starttime = starttime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getStarttime() {
        return starttime;
    }

    public void setStarttime(java.util.Date starttime) {
        this.starttime = starttime;
    }

}
