package com.banba.dictator.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table RECORDING.
 */
public class Recording {

    private Long id;
    /**
     * Not-null value.
     */
    private String name;
    private String fileName;
    private Long fileSize;
    private byte[] recordingData;
    private java.util.Date startTime;
    private java.util.Date endTime;

    public Recording() {
    }

    public Recording(Long id) {
        this.id = id;
    }

    public Recording(Long id, String name, String fileName, Long fileSize, byte[] recordingData, java.util.Date startTime, java.util.Date endTime) {
        this.id = id;
        this.name = name;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.recordingData = recordingData;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getName() {
        return name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setName(String name) {
        this.name = name;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public byte[] getRecordingData() {
        return recordingData;
    }

    public void setRecordingData(byte[] recordingData) {
        this.recordingData = recordingData;
    }

    public java.util.Date getStartTime() {
        return startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getEndTime() {
        return endTime;
    }

    public void setEndTime(java.util.Date endTime) {
        this.endTime = endTime;
    }

}
