package programmer.ie.dictator.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table RECORDING_TEXT.
 */
public class RecordingText {

    private Long id;
    private String name;
    private Long text_time;
    private String words;

    public RecordingText() {
    }

    public RecordingText(Long id) {
        this.id = id;
    }

    public RecordingText(Long id, String name, Long text_time, String words) {
        this.id = id;
        this.name = name;
        this.text_time = text_time;
        this.words = words;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getText_time() {
        return text_time;
    }

    public void setText_time(Long text_time) {
        this.text_time = text_time;
    }

    public String getWords() {
        return words;
    }

    public void setWords(String words) {
        this.words = words;
    }

}
